# Generated by Django 4.1.4 on 2023-02-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='exprity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
