# Generated by Django 4.1.4 on 2023-02-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_description2_alter_notice_exprity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='nepali_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
