# Generated by Django 4.1.4 on 2023-02-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_nepali_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
